### ISSUE TITLE
Change deployment for blender addon

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/data3d-blender-io#1]
- ~~Create deployment for blender addon~~
- ~~Change addon name reference in spaces~~
- ~~Remove addon from spaces repository~~

**Comment by Aadjou** [comment]
@AVGP I like to have your insight on this. I thought, if the repository will go public anyways, we might not need a deployment for this. So the processing-server can directly pull the source from github from the respective branch. 
Else I could setup a jenkins job that deploys a zip on s3.
What do you think?

**Comment by AVGP** [comment]
I agree. Github has a builtin way to get a ZIP of this repository.
This ZIP is available via a URL anyway, so we'd duplicate an existing Github feature for no good reason that I could see :-)

![gh-zip-archive](https://cloud.githubusercontent.com/assets/370246/25717539/0ca3273e-3103-11e7-8540-c6f6af3d7304.png)

And if we don't want processing server to pull the zip, yes, there's the so-called "raw URLs" on github that give, well, raw access to the files via HTTPS

**Comment by Aadjou** [comment]
There will be official Github releases which can be downloaded via HTTP

https://github.com/archilogic-com/data3d-blender-io/releases

ZIP or Tar:
> github.com/archilogic-com/data3d-blender-io/archive/**version-name**_.zip_ or _.tar.gz_
