### ISSUE TITLE
Scale and rotation property from buffer is ignored

### ISSUE THREAD

**Issue by bnjm** [archilogic-com/data3d-blender-io#12]
The furniture piece Tabano (productResourceId: 0b35a7a1-1251-4652-bfdb-62375558db99) displays ok in archilogic and a-frame, but when exported is at the wrong scale

Steps to reproduce: 

```
io3d.furniture
  .get('0b35a7a1-1251-4652-bfdb-62375558db99')
  .then(x => x.info.data3dStorageId)
  .then(io3d.storage.exportDae)
  .then(io3d.utils.processing.whenDone)
  .then(console.log)
// 535e624259ee6b0200000484/processing/2017-11-28_17-34-19_OBcHg4/2017-11-23_22-27-15_HVGQBc.zip
// => open file in 3d editor
```

![screen shot 2017-11-28 at 18 41 45](https://user-images.githubusercontent.com/1694288/33335100-60490ac2-d46c-11e7-9de8-7d2115100d5e.png)

The result is the same with `io3d.storage.exportObj` leading to it being an issue with the importer.

Here's the buffer file:
https://spaces.archilogic.com/3d/template/new?file=/535e624259ee6b0200000484/2017-11-23_22-27_9kuARm/2017-11-23_22-27-15_HVGQBc.gz.data3d.buffer&mode=sdk

**Comment by Aadjou** [comment]
rotated after export
https://spaces.archilogic.com/products?productResourceId=ece347b5-1eb5-4f8f-98f4-34e3910b10ef&view=grid&q=idlab*

**Comment by Aadjou** [comment]
follow up: fix json/hierarchical importer
