### ISSUE TITLE
Weird normals

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/data3d-blender-io#14]
### reproduce:
1. export the yellow couch as data3d buffer from https://spaces.archilogic.com/model/archilogic/ezl15mqb?modelResourceId=f7a3e584-374a-4647-93ba-aa0bd56574df&mode=edit&view-menu=none&main-menu=save&logo=false
2. import data3d buffer in blender using import plugin

### result:
normals look distorted. 
<img width="917" alt="blender" src="https://user-images.githubusercontent.com/6619499/33856340-2146184a-dec8-11e7-8191-15fbcc70b398.png">

### note:
the gray couch is a copy of the yellow one where textures have been deleted. importing **only** the gray couch into blender will result in normals looking correct:
<img width="720" alt="blender" src="https://user-images.githubusercontent.com/6619499/33856714-4a68a782-dec9-11e7-81aa-9a1723e93c29.png">

files for convenience:
[gray_couch.zip](https://github.com/archilogic-com/data3d-blender-io/files/1549594/gray_couch.zip)
[yellow_couch.zip](https://github.com/archilogic-com/data3d-blender-io/files/1549595/yellow_couch.zip)

**Comment by ghost** [comment]
thanks for the bug report! it appears that the normal **map** (or something) gets applied to the mesh **while importing** and **stored** as ``vertex-per-face normals``, freaky.

![normals](https://user-images.githubusercontent.com/13020250/33858922-f7d0e45e-ded1-11e7-87ad-1b5971eb0486.png)

im just assigning myself to this to make sure i get all the memos.

**Comment by Aadjou** [comment]
i would not know of any part of the code that applies normal map as normals though. weird

**Comment by ghost** [comment]
im in the process of loading the importer into my brain anyway, might as well check where these normals are coming from tomorrow. might also be a bug in the [spaces.archilogic.com](https://spaces.archilogic.com) exporter.

**Comment by ghost** [comment]
When i delete the normal maps from the ``textures`` subfolder and import the data3d.json the normals are still messed up. IMO this means the spaces exporter is reading and exporting the wrong normals into the ``data3d`` format, rather than the importer failing.

This could also also explain some of the weird glitches @Aadjou was painfully working around in the importer more convincingly than rounding errors.

**Comment by ghost** [comment]
obj is wrong as well, but differently wrong. what is going on here....
also, when i export both couches at once, they are both wrong no matter the material settings in the ``spaces`` editor. so maybe the normals are still on the original value from simplygon or something?

![obj](https://user-images.githubusercontent.com/13020250/33876815-dafe267a-df26-11e7-9b56-465e4db2c7ef.png)

**Comment by ghost** [comment]
<del>i was able to confirm that the model is actually the problem, rather than any of the software involved at a later step.</del>

<del>the fucked-up normals are not visible in the spaces editor because the realtime shader there ignores it, but they exist from the beginning and dont make sense with the normal maps supplied</del>

**Comment by ghost** [comment]
nope, that was wrong. It looks to me like it is probably the [spaces.archilogic.com](https://spaces.archilogic.com) editor somehow causing this problem, but until we are sure im gonna re-open this issue.

**Comment by mope1** [comment]
i was able to confirm the spaces editor is to blame

**Comment by ghost** [comment]
I decoded the data3d.buffer with the broken normals using ``data3d_utils.py`` and manually inspected the values and it contained vertex normals outside of the ``[ -1 ... 1 ]`` value range. This explains why it looks fucked up, but it's still uncertain if it's a bug in the spaces editor exporter or a bug in the binary format decoder of the python script.

**Comment by ghost** [comment]
i'm gonna open a new issue for the ``convert_tris_to_quads`` being broken, the issue described here has been solved and was not in this software

https://github.com/archilogic-com/data3d-blender-io/issues/17
