### ISSUE TITLE
Check position in nested structures

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/data3d-blender-io#20]
1. Import the attached data3d buffer file in blender:
[xyz.data3d.buffer.zip](https://github.com/archilogic-com/data3d-blender-io/files/3647614/xyz.data3d.buffer.zip)
2. Check position coordinate values of all objects. They should be the same as in the data3d buffer file:
![AE_SDK_0_2_0](https://user-images.githubusercontent.com/6619499/65519236-f91fd200-dee5-11e9-94ff-6715b3f34828.png)

Notes:
- Decoded data3d buffer: https://editor.archilogic.com/3d/template/new?file=/archilogic/tp_test/xyz.data3d.buffer&mode=sdk

**Comment by Jagvisual** [comment]
![image](https://user-images.githubusercontent.com/54317723/65597338-32654a00-df99-11e9-9f0a-1e895bad1968.png)

Only the PLAN coordinates needs a correction,
should be 1.0.0 and it's currently 0.0.0
otherwise the "children's values" are perfectly right:
(level 1, level 2, cube x2) are all correct

**Comment by mredele** [comment]
Fixed in 1300c9a35897662afab63af8f6f9deaffabbaf93
