### ISSUE TITLE
Importing data3d.json file into the Archilogic editor results in error

### ISSUE THREAD

**Issue by david-tran-archilogic** [archilogic-com/data3d-blender-io#5]
Importing the attached data3d.json file with or without the texture folder results in the following error:

![image](https://user-images.githubusercontent.com/23555744/28624498-961f7e84-7219-11e7-9742-8b0554d468cb.png)

[Surrounding.zip](https://github.com/archilogic-com/data3d-blender-io/files/1176738/Surrounding.zip)

The file has been exported with the data3d addon from blender interface

**Comment by ghost** [comment]
gonna check where this issue comes from

**Comment by ghost** [comment]
this issue is old and it appears to be due to a malformed data3d file, maybe the file format changed? this was before my time.

in any case im closing this, i'll be on the lookout for similar issues appearing in our monitoring
